### ISSUE TITLE
Planning session meta issue

### ISSUE THREAD

**Issue by emgrasmeder** [parikhpooja/password_manager_smart_app#1]
Let's lay out some of our goals here and link them to the relevant github issues:

## Side Tasks:
- [ ] Make a back end server that has 3 different endpoints and send a different response for each (#2) 
- [ ] Make a Roman Numeral converter (#9)

## Front End
- [ ] Write 3 different types of functions in javascript (#3)
- [ ] Understanding React state management (#5)

## Infrastructure / Project Overview
- [ ] Be able to draw a diagram of your infrastructure at work (#4)

## Back End
- [ ] Write a back end server in Clojure (#7)
- [ ] Write a custom interceptor for Pedestal (#8)

**Comment by parikhpooja** [comment]
11th Feb:-- Goal to achieve
3 different types of function in javascript. 
error function, .jsx, error function.

be confident about it

**Comment by parikhpooja** [comment]
15th Feb:-- Be able to draw a diagram of sensor cloud project. 
sensor cloud frontend, backend. infrastructure, remotebox, remote.box gps
